### ISSUE TITLE
Meeting

### ISSUE THREAD

**Issue by semey102** [ProPra16/programmierpraktikum-abschlussprojekt-coastal#1]
Hallo zusammen,

ich bin euer Korrektor für das Gruppenprojekt. Ich würde mich gerne am Montag 12:00 oder 14:00 in 25.12.00.82 (Computerraum) kurz mit euch treffen. Das ganze wird ca. 10min dauern.

Könnt ihr mir bitte kurz bescheidgeben, ob der Termin für euch alle passt.

Gruß Sebastian

**Comment by favu100** [comment]
Hallo Sebastian,

mir persönlich würde es am Montag sowohl um 12, als auch um 14 Uhr 
passen. Es ist aber gut möglich, dass es für die anderen Teammitglieder 
ungünstig ist, da sie alle
am Montag frei haben und somit nur für 10 Minuten kommen würden. Aber 
die werden sich sicher noch bei dir melden.

Mit freundlichen Grüßen,

Fabian Vu

Am 2016-07-02 13:12, schrieb semey102:

**Comment by Muuuh219** [comment]
Hallo, ginge es denn auch um 16.30 Uhr am Montag?

Am 2016-07-02 13:12, schrieb semey102:

**Comment by semey102** [comment]
Wir können das Treffen gerne auch auf Dienstag 12:00 verschieben. Würde das bei allen passen?

**Comment by favu100** [comment]
Dienstag haben wir alle noch bis 12:15 Uhr Vorlesung, aber ich habe nichts dagegen 20 Minuten eher zu gehen

**Comment by mawen7** [comment]
Bei Khoa (Muuuh219) und mir passt Dienstag 12:00 Uhr auch.

**Comment by semey102** [comment]
Ok. Dann halten wir mal Dienstag 12:00 Raum 25.12.00.82 (Computerraum) fest.

**Comment by mkduong-ai** [comment]
Passt mir ebenfalls! Gute Vereinbarung!

**Comment by semey102** [comment]
Der raum ist der raum in dem auch die Übungen stattfinden

**Comment by marvindukome** [comment]
Sorry das ich mich erst jetzt melde, aber bei mir passt das am Dienstag auch.
