### ISSUE TITLE
Name und Github-Name

### ISSUE THREAD

**Issue by semey102** [ProPra16/programmierpraktikum-abschlussprojekt-coastal#2]
Hallo zusammen,

könnt ihr mir bitte einmal kurz eure Namen und Github-Namen geben.
Am besten antwortet dazu jeder einmal in der Form:

Vorname Nachname - Github-Name

Danke

**Comment by mawen7** [comment]
Marc Wentzel - mawen7

**Comment by Muuuh219** [comment]
Vorname: Nguyen Khoa
Nachname: Tran
Github-Name: Muuuh219

Am 2016-07-11 12:51, schrieb semey102:

**Comment by favu100** [comment]
Fabian Vu - favu100

Am 2016-07-11 12:51, schrieb semey102:

**Comment by mkduong-ai** [comment]
Manh Khoi Duong - JimmyDuong97

**Comment by marvindukome** [comment]
Marvin Dukome - marvindukome
